---
title: "run-experiments"
author: "aniekmarkus"
date: "2022-05-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Setup instructions

Install the R packages used for the analyses:

```{r install-pkgs, eval=FALSE, echo=TRUE}
install.packages(c("data.table","ggplot2","randomForest","RWeka"))
```

## View settings
```{r}
library(data.table)
library(Explore)
library(ggplot2)
library(plotly)
library(gapminder)

explore_options <- expand.grid(StartRulelength = c(1),
                       EndRulelength = c(5),
                       Parallel = c("yes", "no"),
                       Sorted = c(TRUE, FALSE),
                       Constraint_Accuracy = c("custom"),
                       stringsAsFactors = FALSE) # TODO: check what happens if no solution
# explore_options <- data.frame()

output_path <- paste0(getwd(), "/output/timings_", Sys.Date())

if (!dir.exists(output_path)) {
  dir.create(output_path)
}

# Data to include
# data_name_list <- list.files(path = file.path(getwd(), "data"))
# data_name_list <- c("iris.arff", "vote.arff", "balance-scale.arff", "cover.arff", "asthmastepup.arff", "outpatientmortality.arff")
data_name_list <- c("iris.arff", "cover.arff")

# Methods to test
methods_list <- c("lasso", "explore")
# methods_list <- c("lasso", "randomforest", "ripper", "explore")

```


## Get data
```{r eval=FALSE}
source("code/preparation-data.R")

## GET PLP DATA
```


## Run experiments
```{r eval=TRUE}
source("code/transform-data.R")
source("code/methods.R")
source("code/run-experiments.R")
source("code/helper.R")

output <- runExperiments(output_path, data_name_list, methods_list, explore_options)
```


## Run output
```{r eval=FALSE}
source("code/output.R")
explore_output <- output[[1]]
methods_output <- output[[2]]

plots <- runOutput(explore_output, methods_output)
```



